-- Create a table for Community Posts
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  type text check (type in ('Alert', 'Info', 'Question')) not null,
  user_email text,
  likes int default 0
);

-- Set up Row Level Security (RLS)
alter table public.posts enable row level security;

-- Allow read access to everyone
create policy "Enable read access for all users"
on public.posts for select
using (true);

-- Allow insert access to authenticated users
create policy "Enable insert for authenticated users only"
on public.posts for insert
with check (auth.role() = 'authenticated');
